USE WebAppDB;
GO

IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CONTEXT')
DROP TABLE CONTEXT;
GO

CREATE TABLE [dbo].[CONTEXT]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(20) NOT NULL, 
    [Description] VARCHAR(50) NULL
);
GO

INSERT INTO CONTEXT VALUES (1,'News',NULL);
INSERT INTO CONTEXT VALUES (2,'Sports',NULL);
INSERT INTO CONTEXT VALUES (3,'Entertainment',NULL);
INSERT INTO CONTEXT VALUES (4,'Politics',NULL);
INSERT INTO CONTEXT VALUES (5,'Fashion',NULL);
INSERT INTO CONTEXT VALUES (6,'Travel',NULL);
INSERT INTO CONTEXT VALUES (7,'Person',NULL);
INSERT INTO CONTEXT VALUES (8,'Clubs',NULL);
INSERT INTO CONTEXT VALUES (9,'Country',NULL);
INSERT INTO CONTEXT VALUES (10,'Magazines',NULL);
GO

GRANT SELECT ON [dbo].[CONTEXT] TO [webappuser];
GO


IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TAGS')
DROP TABLE TAGS;
GO

CREATE TABLE [dbo].[TAGS]
(
	[Value] VARCHAR(20) NOT NULL PRIMARY KEY
);
GO

INSERT INTO TAGS VALUES ('News');
INSERT INTO TAGS VALUES ('Actual');
INSERT INTO TAGS VALUES ('Latest');
INSERT INTO TAGS VALUES ('Breaking');
INSERT INTO TAGS VALUES ('Headlines');
INSERT INTO TAGS VALUES ('Source');
INSERT INTO TAGS VALUES ('Media');
GO

GRANT SELECT ON [dbo].[TAGS] TO [webappuser];
GO

IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CONT_TAG')
DROP TABLE CONT_TAG;
GO

CREATE TABLE [dbo].[CONT_TAG]
(
	[Id] INT NOT NULL FOREIGN KEY(Id) REFERENCES CONTEXT(Id),
	[Value] VARCHAR(20) NOT NULL FOREIGN KEY(Value) REFERENCES TAGS(Value),
);
GO

INSERT INTO CONT_TAG VALUES (1,'News');
INSERT INTO CONT_TAG VALUES (1,'Actual');
INSERT INTO CONT_TAG VALUES (1,'Latest');
INSERT INTO CONT_TAG VALUES (1,'Breaking');
INSERT INTO CONT_TAG VALUES (1,'Headlines');
INSERT INTO CONT_TAG VALUES (1,'Source');
INSERT INTO CONT_TAG VALUES (1,'Media');
GO

GRANT SELECT ON [dbo].[CONT_TAG] TO [webappuser];
GO
