IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CONTEXT')
DROP TABLE CONTEXT;
GO

CREATE TABLE [dbo].[CONTEXT]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(20) NOT NULL, 
    [Description] VARCHAR(50) NULL
);
GO

INSERT INTO CONTEXT VALUES (1,'News',NULL);
INSERT INTO CONTEXT VALUES (2,'Sports',NULL);
INSERT INTO CONTEXT VALUES (3,'Entertainment',NULL);
INSERT INTO CONTEXT VALUES (4,'Politics',NULL);
INSERT INTO CONTEXT VALUES (5,'Fashion',NULL);
INSERT INTO CONTEXT VALUES (6,'Travel',NULL);
INSERT INTO CONTEXT VALUES (7,'Person',NULL);
INSERT INTO CONTEXT VALUES (8,'Clubs',NULL);
INSERT INTO CONTEXT VALUES (9,'Country',NULL);
INSERT INTO CONTEXT VALUES (10,'Magazines',NULL);

GO